# Generated by Django 5.2.7 on 2025-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
