# Generated by Django 5.2.7 on 2025-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image_url',
            field=models.URLField(max_length=10000),
        ),
    ]
